language: python
python: "2.7"
install: pip install -r ./tracktrains/requirements/build.txt
before_script:
    - psql -c 'create database tracktrains;' -U postgres
    - python manage.py syncdb --noinput
    - python manage.py migrate
script: ./cov.sh
after_success: coveralls
